//
//  RoutePOIs.swift
//  StrideBy
//
//  Created by Andrew Ginn on 2/13/26.
//

import CoreLocation

// MARK: - Points of Interest for Look Around

// Each route has curated POIs placed at real towns along the highway corridor,
// spaced every ~30-50 miles. These are towns/cities likely to have Apple Look
// Around coverage, making the "Look Around" and "Nearest Place" features work well.

extension RunRoute {

    // ───────────────────────────────────────────────
    // NYC → LA — I-80/I-76/I-70/I-15/I-80/CA-99
    // ~55 POIs along the route
    // ───────────────────────────────────────────────

    static let nycToLAPOIs: [Landmark] = [
        Landmark(id: "poi-nyc-newark", name: "Newark", state: "NJ",
                 coordinate: CLLocationCoordinate2D(latitude: 40.7357, longitude: -74.1724),
                 distanceFromStartMiles: 10),
        Landmark(id: "poi-nyc-edison", name: "Edison", state: "NJ",
                 coordinate: CLLocationCoordinate2D(latitude: 40.5187, longitude: -74.4121),
                 distanceFromStartMiles: 35),
        Landmark(id: "poi-nyc-easton", name: "Easton", state: "PA",
                 coordinate: CLLocationCoordinate2D(latitude: 40.6910, longitude: -75.2207),
                 distanceFromStartMiles: 75),
        Landmark(id: "poi-nyc-allentown", name: "Allentown", state: "PA",
                 coordinate: CLLocationCoordinate2D(latitude: 40.6023, longitude: -75.4714),
                 distanceFromStartMiles: 95),
        Landmark(id: "poi-nyc-reading", name: "Reading", state: "PA",
                 coordinate: CLLocationCoordinate2D(latitude: 40.3357, longitude: -75.9269),
                 distanceFromStartMiles: 130),
        Landmark(id: "poi-nyc-harrisburg", name: "Harrisburg", state: "PA",
                 coordinate: CLLocationCoordinate2D(latitude: 40.2732, longitude: -76.8867),
                 distanceFromStartMiles: 185),
        Landmark(id: "poi-nyc-carlisle", name: "Carlisle", state: "PA",
                 coordinate: CLLocationCoordinate2D(latitude: 40.2015, longitude: -77.1886),
                 distanceFromStartMiles: 210),
        Landmark(id: "poi-nyc-chambersburg", name: "Chambersburg", state: "PA",
                 coordinate: CLLocationCoordinate2D(latitude: 39.9376, longitude: -77.6611),
                 distanceFromStartMiles: 245),
        Landmark(id: "poi-nyc-bedford", name: "Bedford", state: "PA",
                 coordinate: CLLocationCoordinate2D(latitude: 40.0186, longitude: -78.5039),
                 distanceFromStartMiles: 290),
        Landmark(id: "poi-nyc-somerset", name: "Somerset", state: "PA",
                 coordinate: CLLocationCoordinate2D(latitude: 40.0087, longitude: -79.0781),
                 distanceFromStartMiles: 325),
        Landmark(id: "poi-nyc-pittsburgh", name: "Pittsburgh", state: "PA",
                 coordinate: CLLocationCoordinate2D(latitude: 40.4406, longitude: -79.9959),
                 distanceFromStartMiles: 370),
        Landmark(id: "poi-nyc-canton", name: "Canton", state: "OH",
                 coordinate: CLLocationCoordinate2D(latitude: 40.7989, longitude: -81.3784),
                 distanceFromStartMiles: 430),
        Landmark(id: "poi-nyc-akron", name: "Akron", state: "OH",
                 coordinate: CLLocationCoordinate2D(latitude: 41.0814, longitude: -81.5190),
                 distanceFromStartMiles: 460),
        Landmark(id: "poi-nyc-mansfield", name: "Mansfield", state: "OH",
                 coordinate: CLLocationCoordinate2D(latitude: 40.7581, longitude: -82.5154),
                 distanceFromStartMiles: 510),
        Landmark(id: "poi-nyc-columbus", name: "Columbus", state: "OH",
                 coordinate: CLLocationCoordinate2D(latitude: 39.9612, longitude: -82.9988),
                 distanceFromStartMiles: 540),
        Landmark(id: "poi-nyc-springfield-oh", name: "Springfield", state: "OH",
                 coordinate: CLLocationCoordinate2D(latitude: 39.9242, longitude: -83.8088),
                 distanceFromStartMiles: 590),
        Landmark(id: "poi-nyc-dayton", name: "Dayton", state: "OH",
                 coordinate: CLLocationCoordinate2D(latitude: 39.7589, longitude: -84.1916),
                 distanceFromStartMiles: 620),
        Landmark(id: "poi-nyc-richmond-in", name: "Richmond", state: "IN",
                 coordinate: CLLocationCoordinate2D(latitude: 39.8289, longitude: -84.8902),
                 distanceFromStartMiles: 665),
        Landmark(id: "poi-nyc-indianapolis", name: "Indianapolis", state: "IN",
                 coordinate: CLLocationCoordinate2D(latitude: 39.7684, longitude: -86.1581),
                 distanceFromStartMiles: 740),
        Landmark(id: "poi-nyc-terrehaute", name: "Terre Haute", state: "IN",
                 coordinate: CLLocationCoordinate2D(latitude: 39.4667, longitude: -87.4139),
                 distanceFromStartMiles: 815),
        Landmark(id: "poi-nyc-effingham", name: "Effingham", state: "IL",
                 coordinate: CLLocationCoordinate2D(latitude: 39.1200, longitude: -88.5434),
                 distanceFromStartMiles: 870),
        Landmark(id: "poi-nyc-stlouis", name: "St. Louis", state: "MO",
                 coordinate: CLLocationCoordinate2D(latitude: 38.6270, longitude: -90.1994),
                 distanceFromStartMiles: 950),
        Landmark(id: "poi-nyc-columbia-mo", name: "Columbia", state: "MO",
                 coordinate: CLLocationCoordinate2D(latitude: 38.9517, longitude: -92.3341),
                 distanceFromStartMiles: 1020),
        Landmark(id: "poi-nyc-kansascity", name: "Kansas City", state: "MO",
                 coordinate: CLLocationCoordinate2D(latitude: 39.0997, longitude: -94.5786),
                 distanceFromStartMiles: 1200),
        Landmark(id: "poi-nyc-topeka", name: "Topeka", state: "KS",
                 coordinate: CLLocationCoordinate2D(latitude: 39.0473, longitude: -95.6752),
                 distanceFromStartMiles: 1260),
        Landmark(id: "poi-nyc-junction-city", name: "Junction City", state: "KS",
                 coordinate: CLLocationCoordinate2D(latitude: 39.0286, longitude: -96.8314),
                 distanceFromStartMiles: 1320),
        Landmark(id: "poi-nyc-salina", name: "Salina", state: "KS",
                 coordinate: CLLocationCoordinate2D(latitude: 38.8403, longitude: -97.6114),
                 distanceFromStartMiles: 1370),
        Landmark(id: "poi-nyc-hays", name: "Hays", state: "KS",
                 coordinate: CLLocationCoordinate2D(latitude: 38.8791, longitude: -99.3268),
                 distanceFromStartMiles: 1430),
        Landmark(id: "poi-nyc-oakley", name: "Oakley", state: "KS",
                 coordinate: CLLocationCoordinate2D(latitude: 39.1314, longitude: -100.8522),
                 distanceFromStartMiles: 1480),
        Landmark(id: "poi-nyc-burlington", name: "Burlington", state: "CO",
                 coordinate: CLLocationCoordinate2D(latitude: 39.3058, longitude: -102.2693),
                 distanceFromStartMiles: 1530),
        Landmark(id: "poi-nyc-limon", name: "Limon", state: "CO",
                 coordinate: CLLocationCoordinate2D(latitude: 39.2639, longitude: -103.6922),
                 distanceFromStartMiles: 1580),
        Landmark(id: "poi-nyc-denver", name: "Denver", state: "CO",
                 coordinate: CLLocationCoordinate2D(latitude: 39.7392, longitude: -104.9903),
                 distanceFromStartMiles: 1630),
        Landmark(id: "poi-nyc-idahosprings", name: "Idaho Springs", state: "CO",
                 coordinate: CLLocationCoordinate2D(latitude: 39.7425, longitude: -105.5133),
                 distanceFromStartMiles: 1665),
        Landmark(id: "poi-nyc-vail", name: "Vail", state: "CO",
                 coordinate: CLLocationCoordinate2D(latitude: 39.6403, longitude: -106.3742),
                 distanceFromStartMiles: 1730),
        Landmark(id: "poi-nyc-glenwood", name: "Glenwood Springs", state: "CO",
                 coordinate: CLLocationCoordinate2D(latitude: 39.5505, longitude: -107.3248),
                 distanceFromStartMiles: 1790),
        Landmark(id: "poi-nyc-grandjunction", name: "Grand Junction", state: "CO",
                 coordinate: CLLocationCoordinate2D(latitude: 39.0639, longitude: -108.5506),
                 distanceFromStartMiles: 1850),
        Landmark(id: "poi-nyc-greenriver", name: "Green River", state: "UT",
                 coordinate: CLLocationCoordinate2D(latitude: 38.9933, longitude: -110.1530),
                 distanceFromStartMiles: 1920),
        Landmark(id: "poi-nyc-provo", name: "Provo", state: "UT",
                 coordinate: CLLocationCoordinate2D(latitude: 40.2338, longitude: -111.6585),
                 distanceFromStartMiles: 1985),
        Landmark(id: "poi-nyc-slc", name: "Salt Lake City", state: "UT",
                 coordinate: CLLocationCoordinate2D(latitude: 40.7608, longitude: -111.8910),
                 distanceFromStartMiles: 2020),
        Landmark(id: "poi-nyc-wendover", name: "Wendover", state: "UT",
                 coordinate: CLLocationCoordinate2D(latitude: 40.7440, longitude: -113.0861),
                 distanceFromStartMiles: 2100),
        Landmark(id: "poi-nyc-elko", name: "Elko", state: "NV",
                 coordinate: CLLocationCoordinate2D(latitude: 40.8410, longitude: -115.7631),
                 distanceFromStartMiles: 2190),
        Landmark(id: "poi-nyc-winnemucca", name: "Winnemucca", state: "NV",
                 coordinate: CLLocationCoordinate2D(latitude: 40.6847, longitude: -117.4168),
                 distanceFromStartMiles: 2260),
        Landmark(id: "poi-nyc-lovelockfernley", name: "Fernley", state: "NV",
                 coordinate: CLLocationCoordinate2D(latitude: 39.6080, longitude: -119.2519),
                 distanceFromStartMiles: 2340),
        Landmark(id: "poi-nyc-reno", name: "Reno", state: "NV",
                 coordinate: CLLocationCoordinate2D(latitude: 39.5296, longitude: -119.8138),
                 distanceFromStartMiles: 2370),
        Landmark(id: "poi-nyc-sacramento", name: "Sacramento", state: "CA",
                 coordinate: CLLocationCoordinate2D(latitude: 38.5816, longitude: -121.4944),
                 distanceFromStartMiles: 2430),
        Landmark(id: "poi-nyc-stockton", name: "Stockton", state: "CA",
                 coordinate: CLLocationCoordinate2D(latitude: 37.9577, longitude: -121.2908),
                 distanceFromStartMiles: 2480),
        Landmark(id: "poi-nyc-merced", name: "Merced", state: "CA",
                 coordinate: CLLocationCoordinate2D(latitude: 37.3022, longitude: -120.4830),
                 distanceFromStartMiles: 2530),
        Landmark(id: "poi-nyc-fresno", name: "Fresno", state: "CA",
                 coordinate: CLLocationCoordinate2D(latitude: 36.7783, longitude: -119.7871),
                 distanceFromStartMiles: 2580),
        Landmark(id: "poi-nyc-visalia", name: "Visalia", state: "CA",
                 coordinate: CLLocationCoordinate2D(latitude: 36.3302, longitude: -119.2921),
                 distanceFromStartMiles: 2615),
        Landmark(id: "poi-nyc-bakersfield", name: "Bakersfield", state: "CA",
                 coordinate: CLLocationCoordinate2D(latitude: 35.3733, longitude: -119.0187),
                 distanceFromStartMiles: 2670),
        Landmark(id: "poi-nyc-lancaster", name: "Lancaster", state: "CA",
                 coordinate: CLLocationCoordinate2D(latitude: 34.6868, longitude: -118.1542),
                 distanceFromStartMiles: 2720),
        Landmark(id: "poi-nyc-santaclarita", name: "Santa Clarita", state: "CA",
                 coordinate: CLLocationCoordinate2D(latitude: 34.3917, longitude: -118.5426),
                 distanceFromStartMiles: 2755),
        Landmark(id: "poi-nyc-la", name: "Los Angeles", state: "CA",
                 coordinate: CLLocationCoordinate2D(latitude: 34.0522, longitude: -118.2437),
                 distanceFromStartMiles: 2790),
    ]

    // ───────────────────────────────────────────────
    // London → Istanbul — E40/E5 corridor
    // ~35 POIs
    // ───────────────────────────────────────────────

    static let londonToIstanbulPOIs: [Landmark] = [
        Landmark(id: "poi-eur-dover", name: "Dover", state: "England",
                 coordinate: CLLocationCoordinate2D(latitude: 51.1279, longitude: 1.3134),
                 distanceFromStartMiles: 75),
        Landmark(id: "poi-eur-calais", name: "Calais", state: "France",
                 coordinate: CLLocationCoordinate2D(latitude: 50.9513, longitude: 1.8587),
                 distanceFromStartMiles: 110),
        Landmark(id: "poi-eur-amiens", name: "Amiens", state: "France",
                 coordinate: CLLocationCoordinate2D(latitude: 49.8988, longitude: 2.2957),
                 distanceFromStartMiles: 185),
        Landmark(id: "poi-eur-paris", name: "Paris", state: "France",
                 coordinate: CLLocationCoordinate2D(latitude: 48.8566, longitude: 2.3522),
                 distanceFromStartMiles: 280),
        Landmark(id: "poi-eur-reims", name: "Reims", state: "France",
                 coordinate: CLLocationCoordinate2D(latitude: 49.2583, longitude: 4.0317),
                 distanceFromStartMiles: 340),
        Landmark(id: "poi-eur-metz", name: "Metz", state: "France",
                 coordinate: CLLocationCoordinate2D(latitude: 49.1193, longitude: 6.1757),
                 distanceFromStartMiles: 410),
        Landmark(id: "poi-eur-strasbourg", name: "Strasbourg", state: "France",
                 coordinate: CLLocationCoordinate2D(latitude: 48.5734, longitude: 7.7521),
                 distanceFromStartMiles: 490),
        Landmark(id: "poi-eur-stuttgart", name: "Stuttgart", state: "Germany",
                 coordinate: CLLocationCoordinate2D(latitude: 48.7758, longitude: 9.1829),
                 distanceFromStartMiles: 560),
        Landmark(id: "poi-eur-ulm", name: "Ulm", state: "Germany",
                 coordinate: CLLocationCoordinate2D(latitude: 48.4011, longitude: 9.9876),
                 distanceFromStartMiles: 610),
        Landmark(id: "poi-eur-augsburg", name: "Augsburg", state: "Germany",
                 coordinate: CLLocationCoordinate2D(latitude: 48.3705, longitude: 10.8978),
                 distanceFromStartMiles: 650),
        Landmark(id: "poi-eur-munich", name: "Munich", state: "Germany",
                 coordinate: CLLocationCoordinate2D(latitude: 48.1351, longitude: 11.5820),
                 distanceFromStartMiles: 680),
        Landmark(id: "poi-eur-salzburg", name: "Salzburg", state: "Austria",
                 coordinate: CLLocationCoordinate2D(latitude: 47.8095, longitude: 13.0550),
                 distanceFromStartMiles: 750),
        Landmark(id: "poi-eur-linz", name: "Linz", state: "Austria",
                 coordinate: CLLocationCoordinate2D(latitude: 48.3064, longitude: 14.2858),
                 distanceFromStartMiles: 820),
        Landmark(id: "poi-eur-vienna", name: "Vienna", state: "Austria",
                 coordinate: CLLocationCoordinate2D(latitude: 48.2082, longitude: 16.3738),
                 distanceFromStartMiles: 910),
        Landmark(id: "poi-eur-bratislava", name: "Bratislava", state: "Slovakia",
                 coordinate: CLLocationCoordinate2D(latitude: 48.1486, longitude: 17.1077),
                 distanceFromStartMiles: 950),
        Landmark(id: "poi-eur-gyor", name: "Gyor", state: "Hungary",
                 coordinate: CLLocationCoordinate2D(latitude: 47.6849, longitude: 17.6351),
                 distanceFromStartMiles: 990),
        Landmark(id: "poi-eur-budapest", name: "Budapest", state: "Hungary",
                 coordinate: CLLocationCoordinate2D(latitude: 47.4979, longitude: 19.0402),
                 distanceFromStartMiles: 1080),
        Landmark(id: "poi-eur-kecskemet", name: "Kecskemet", state: "Hungary",
                 coordinate: CLLocationCoordinate2D(latitude: 46.8964, longitude: 19.6913),
                 distanceFromStartMiles: 1130),
        Landmark(id: "poi-eur-szeged", name: "Szeged", state: "Hungary",
                 coordinate: CLLocationCoordinate2D(latitude: 46.2530, longitude: 20.1414),
                 distanceFromStartMiles: 1180),
        Landmark(id: "poi-eur-novisad", name: "Novi Sad", state: "Serbia",
                 coordinate: CLLocationCoordinate2D(latitude: 45.2671, longitude: 19.8335),
                 distanceFromStartMiles: 1220),
        Landmark(id: "poi-eur-belgrade", name: "Belgrade", state: "Serbia",
                 coordinate: CLLocationCoordinate2D(latitude: 44.7866, longitude: 20.4489),
                 distanceFromStartMiles: 1270),
        Landmark(id: "poi-eur-nis", name: "Nis", state: "Serbia",
                 coordinate: CLLocationCoordinate2D(latitude: 43.3209, longitude: 21.8958),
                 distanceFromStartMiles: 1370),
        Landmark(id: "poi-eur-pirot", name: "Pirot", state: "Serbia",
                 coordinate: CLLocationCoordinate2D(latitude: 43.1531, longitude: 22.5856),
                 distanceFromStartMiles: 1410),
        Landmark(id: "poi-eur-sofia", name: "Sofia", state: "Bulgaria",
                 coordinate: CLLocationCoordinate2D(latitude: 42.6977, longitude: 23.3219),
                 distanceFromStartMiles: 1490),
        Landmark(id: "poi-eur-plovdiv", name: "Plovdiv", state: "Bulgaria",
                 coordinate: CLLocationCoordinate2D(latitude: 42.1497, longitude: 24.7500),
                 distanceFromStartMiles: 1570),
        Landmark(id: "poi-eur-svilengrad", name: "Svilengrad", state: "Bulgaria",
                 coordinate: CLLocationCoordinate2D(latitude: 41.7654, longitude: 26.2017),
                 distanceFromStartMiles: 1640),
        Landmark(id: "poi-eur-edirne", name: "Edirne", state: "Turkey",
                 coordinate: CLLocationCoordinate2D(latitude: 41.6772, longitude: 26.5557),
                 distanceFromStartMiles: 1670),
        Landmark(id: "poi-eur-corlu", name: "Corlu", state: "Turkey",
                 coordinate: CLLocationCoordinate2D(latitude: 41.1591, longitude: 27.8003),
                 distanceFromStartMiles: 1720),
        Landmark(id: "poi-eur-istanbul", name: "Istanbul", state: "Turkey",
                 coordinate: CLLocationCoordinate2D(latitude: 41.0082, longitude: 28.9784),
                 distanceFromStartMiles: 1770),
    ]

    // ───────────────────────────────────────────────
    // Tokyo → Kyoto — Tokaido corridor
    // ~10 POIs
    // ───────────────────────────────────────────────

    static let tokyoToKyotoPOIs: [Landmark] = [
        Landmark(id: "poi-jpn-yokohama", name: "Yokohama", state: "Kanagawa",
                 coordinate: CLLocationCoordinate2D(latitude: 35.4437, longitude: 139.6380),
                 distanceFromStartMiles: 18),
        Landmark(id: "poi-jpn-kamakura", name: "Kamakura", state: "Kanagawa",
                 coordinate: CLLocationCoordinate2D(latitude: 35.3293, longitude: 139.4803),
                 distanceFromStartMiles: 30),
        Landmark(id: "poi-jpn-odawara", name: "Odawara", state: "Kanagawa",
                 coordinate: CLLocationCoordinate2D(latitude: 35.2564, longitude: 139.1550),
                 distanceFromStartMiles: 50),
        Landmark(id: "poi-jpn-mishima", name: "Mishima", state: "Shizuoka",
                 coordinate: CLLocationCoordinate2D(latitude: 35.1006, longitude: 138.8606),
                 distanceFromStartMiles: 65),
        Landmark(id: "poi-jpn-shizuoka", name: "Shizuoka", state: "Shizuoka",
                 coordinate: CLLocationCoordinate2D(latitude: 34.9756, longitude: 138.3827),
                 distanceFromStartMiles: 110),
        Landmark(id: "poi-jpn-hamamatsu", name: "Hamamatsu", state: "Shizuoka",
                 coordinate: CLLocationCoordinate2D(latitude: 34.7108, longitude: 137.7261),
                 distanceFromStartMiles: 165),
        Landmark(id: "poi-jpn-toyohashi", name: "Toyohashi", state: "Aichi",
                 coordinate: CLLocationCoordinate2D(latitude: 34.7303, longitude: 137.3948),
                 distanceFromStartMiles: 190),
        Landmark(id: "poi-jpn-nagoya", name: "Nagoya", state: "Aichi",
                 coordinate: CLLocationCoordinate2D(latitude: 35.1815, longitude: 136.9066),
                 distanceFromStartMiles: 220),
        Landmark(id: "poi-jpn-suzuka", name: "Suzuka", state: "Mie",
                 coordinate: CLLocationCoordinate2D(latitude: 34.9672, longitude: 136.6245),
                 distanceFromStartMiles: 255),
        Landmark(id: "poi-jpn-kyoto", name: "Kyoto", state: "Kyoto",
                 coordinate: CLLocationCoordinate2D(latitude: 35.0116, longitude: 135.7681),
                 distanceFromStartMiles: 300),
    ]

    // ───────────────────────────────────────────────
    // Reykjavik → Vik — Route 1 south coast
    // ~4 POIs (short route, fewer towns)
    // ───────────────────────────────────────────────

    static let reykjavikToVikPOIs: [Landmark] = [
        Landmark(id: "poi-ice-hveragerdi", name: "Hveragerdi", state: "South Iceland",
                 coordinate: CLLocationCoordinate2D(latitude: 64.0153, longitude: -21.1874),
                 distanceFromStartMiles: 25),
        Landmark(id: "poi-ice-selfoss", name: "Selfoss", state: "South Iceland",
                 coordinate: CLLocationCoordinate2D(latitude: 63.9461, longitude: -20.6600),
                 distanceFromStartMiles: 37),
        Landmark(id: "poi-ice-hella", name: "Hella", state: "South Iceland",
                 coordinate: CLLocationCoordinate2D(latitude: 63.7626, longitude: -20.2290),
                 distanceFromStartMiles: 60),
        Landmark(id: "poi-ice-hvolsvollur", name: "Hvolsvollur", state: "South Iceland",
                 coordinate: CLLocationCoordinate2D(latitude: 63.6335, longitude: -19.8262),
                 distanceFromStartMiles: 75),
        Landmark(id: "poi-ice-skogafoss", name: "Skogafoss", state: "South Iceland",
                 coordinate: CLLocationCoordinate2D(latitude: 63.5320, longitude: -19.5112),
                 distanceFromStartMiles: 85),
        Landmark(id: "poi-ice-vik", name: "Vik", state: "South Iceland",
                 coordinate: CLLocationCoordinate2D(latitude: 63.4186, longitude: -19.0060),
                 distanceFromStartMiles: 110),
    ]

    // ───────────────────────────────────────────────
    // Sydney → Melbourne — Hume Highway (M31/M1)
    // ~12 POIs
    // ───────────────────────────────────────────────

    static let sydneyToMelbournePOIs: [Landmark] = [
        Landmark(id: "poi-aus-campbelltown", name: "Campbelltown", state: "NSW",
                 coordinate: CLLocationCoordinate2D(latitude: -34.0588, longitude: 150.8052),
                 distanceFromStartMiles: 35),
        Landmark(id: "poi-aus-mittagong", name: "Mittagong", state: "NSW",
                 coordinate: CLLocationCoordinate2D(latitude: -34.2890, longitude: 150.4541),
                 distanceFromStartMiles: 70),
        Landmark(id: "poi-aus-goulburn", name: "Goulburn", state: "NSW",
                 coordinate: CLLocationCoordinate2D(latitude: -34.7515, longitude: 149.7185),
                 distanceFromStartMiles: 120),
        Landmark(id: "poi-aus-yass", name: "Yass", state: "NSW",
                 coordinate: CLLocationCoordinate2D(latitude: -34.8580, longitude: 149.3575),
                 distanceFromStartMiles: 155),
        Landmark(id: "poi-aus-canberra", name: "Canberra", state: "ACT",
                 coordinate: CLLocationCoordinate2D(latitude: -35.2809, longitude: 149.1300),
                 distanceFromStartMiles: 180),
        Landmark(id: "poi-aus-gundagai", name: "Gundagai", state: "NSW",
                 coordinate: CLLocationCoordinate2D(latitude: -35.0652, longitude: 148.0975),
                 distanceFromStartMiles: 240),
        Landmark(id: "poi-aus-holbrook", name: "Holbrook", state: "NSW",
                 coordinate: CLLocationCoordinate2D(latitude: -35.9344, longitude: 147.9535),
                 distanceFromStartMiles: 310),
        Landmark(id: "poi-aus-albury", name: "Albury", state: "NSW",
                 coordinate: CLLocationCoordinate2D(latitude: -36.3690, longitude: 146.9235),
                 distanceFromStartMiles: 355),
        Landmark(id: "poi-aus-wangaratta", name: "Wangaratta", state: "VIC",
                 coordinate: CLLocationCoordinate2D(latitude: -36.5400, longitude: 146.4268),
                 distanceFromStartMiles: 420),
        Landmark(id: "poi-aus-benalla", name: "Benalla", state: "VIC",
                 coordinate: CLLocationCoordinate2D(latitude: -36.5518, longitude: 145.9816),
                 distanceFromStartMiles: 450),
        Landmark(id: "poi-aus-seymour", name: "Seymour", state: "VIC",
                 coordinate: CLLocationCoordinate2D(latitude: -37.0265, longitude: 145.1392),
                 distanceFromStartMiles: 500),
        Landmark(id: "poi-aus-melbourne", name: "Melbourne", state: "VIC",
                 coordinate: CLLocationCoordinate2D(latitude: -37.8136, longitude: 144.9631),
                 distanceFromStartMiles: 545),
    ]
}
